CREATE DATABASE IF NOT EXISTS electroaid;
USE electroaid;

CREATE TABLE IF NOT EXISTS clients (
id INT AUTO_INCREMENT PRIMARY KEY,

CLIENT_NAME VARCHAR(255) NOT NULL,
CLIENT_EMAIL VARCHAR(255) UNIQUE NOT NULL,
CLIENT_PHONE_NUMBER VARCHAR(50) UNIQUE,
CLIENT_PROFILE_IMAGE TEXT,

CLIENT_PASSWORD VARCHAR(255),

status VARCHAR(50) DEFAULT 'active',

createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

INDEX idx_email (CLIENT_EMAIL),
INDEX idx_phone (CLIENT_PHONE_NUMBER),
INDEX idx_status (status)

);